server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-order-service
# 配置Feign客户端连接超时时间(Feign默认支持Ribbon
ribbon:
#  建立连接的超时时间(ms)
  ReadTimeout: 5000
#  建立连接后服务器读取到可用资源的时间 
  connectTimeout: 5000